# Application
quarkus.application.name=incident-service
quarkus.http.port=8081

# PostgreSQL (Reactive)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.reactive.url=postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:incident_db}
# JDBC for Liquibase only
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:incident_db}

# Liquibase
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog/db.changelog-master.xml

# Hibernate Reactive
quarkus.hibernate-orm.database.generation=none

# Keycloak OIDC
quarkus.oidc.auth-server-url=${KEYCLOAK_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:support}
quarkus.oidc.client-id=incident-service
quarkus.oidc.credentials.secret=${OIDC_SECRET:secret}
quarkus.oidc.tls.verification=none

# gRPC clients
quarkus.grpc.clients.user-service.host=${USER_SERVICE_HOST:localhost}
quarkus.grpc.clients.user-service.port=${USER_SERVICE_GRPC_PORT:9007}
quarkus.grpc.clients.image-service.host=${IMAGE_SERVICE_HOST:localhost}
quarkus.grpc.clients.image-service.port=${IMAGE_SERVICE_GRPC_PORT:9008}

# Kafka
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP:localhost:29092}
mp.messaging.outgoing.incident-events.connector=smallrye-kafka
mp.messaging.outgoing.incident-events.topic=incident-events
mp.messaging.outgoing.incident-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# gRPC server ? switch to single HTTP server and change port away from 9000 (MinIO)
quarkus.grpc.server.use-separate-server=false
quarkus.grpc.server.port=9090

# Swagger ? Bearer token authorization
quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=bearerAuth
quarkus.smallrye-openapi.security-scheme-description=JWT Bearer token
quarkus.smallrye-openapi.auto-add-security=true

# Keycloak roles mapping ? ???? ????? ? realm_access.roles
quarkus.oidc.roles.role-claim-path=realm_access/roles

# Multipart file upload
quarkus.http.limits.max-body-size=10M
quarkus.http.body.handle-file-uploads=true
quarkus.http.body.uploads-directory=${java.io.tmpdir}