# Application
quarkus.application.name=user-service
quarkus.http.port=8082

# PostgreSQL (Reactive)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.reactive.url=postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:user_db}
# JDBC for Liquibase only
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:user_db}

# Liquibase
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog/db.changelog-master.xml

# Hibernate Reactive
quarkus.hibernate-orm.database.generation=none

# Keycloak OIDC
quarkus.oidc.auth-server-url=${KEYCLOAK_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:support}
quarkus.oidc.client-id=user-service
quarkus.oidc.credentials.secret=${OIDC_SECRET:0OB7pr2FvhwZNT1N0cUG3Qc9JU0oH9zM}
quarkus.oidc.tls.verification=none
quarkus.oidc.roles.role-claim-path=realm_access/roles

# Keycloak Admin API
keycloak.admin.url=${KEYCLOAK_URL:http://localhost:8080}
keycloak.admin.realm=${KEYCLOAK_REALM:support}
keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:user-service}
keycloak.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET:0OB7pr2FvhwZNT1N0cUG3Qc9JU0oH9zM}

# gRPC server HTTP (9007)
quarkus.grpc.server.use-separate-server=true
quarkus.grpc.server.port=9007

# Swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=bearerAuth
quarkus.smallrye-openapi.security-scheme-description=JWT Bearer token
quarkus.smallrye-openapi.auto-add-security=true